[project]
name = "opg-dora-metrics"
dynamic = ["version"]
description = ""
authors = []
requires-python = "^3.10"

packages = [
    { include = "dora" },
    { include = "github" },
    { include = "timer" },
]
